language: python
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
install:
  - sudo apt-get install libgdal-dev
  - pip install matplotlib
  - python setup.py install

script:
  - /usr/bin/env python tests/test.py
