language: python
dist: trusty
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - sudo apt-get install libgdal-dev
  - "python setup.py install"

script:
  - /usr/bin/env python tests/test.py
